//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MODERATE.RC
//
#define CID_OK                          1
#define CID_CANCEL                      2
#define IDD_WorkSpace                   103
#define IDB_BITMAP2                     107
#define IDB_CREATE_CONF_16              108
#define IDB_EDIT_TOPIC_16               109
#define IDB_EDIT_FILELIST_16            110
#define IDB_SETTINGS_16                 111
#define IDB_HELP_16                     112
#define IDB_CREATE_CONF_24              113
#define IDI_ARROW                       114
#define IDB_EDIT_FILELIST_24            115
#define IDC_DRAG                        115
#define IDB_EDIT_TOPIC_24               116
#define IDC_NODRAG                      116
#define IDB_HELP_24                     117
#define IDB_SETTINGS_24                 118
#define IDB_ABOUT_16                    119
#define IDB_ABOUT_24                    120
#define IDB_HELP_CONTENTS_24            121
#define IDB_HELP_CONTENTS_16            122
#define IDB_HELP_ABOUT_16               123
#define IDB_HELP_ABOUT_24               124
#define CA_IID_SCALES                   125
#define CID_VERSIONTEXT                 300
#define CID_CONFERENCE                  302
#define CID_INSERT                      306
#define CID_APPEND                      307
#define CID_EDIT                        308
#define CID_MOVE_UP                     309
#define CID_MOVE_DOWN                   310
#define CID_EXPORT                      311
#define CID_DELETE                      312
#define CID_UPDATE_FILE                 313
#define CID_DOWNLOAD                    314
#define CID_DOWNLOAD_LISTS              315
#define CID_FLIST_FRAME                 316
#define CID_ERR_FILE                    317
#define CID_SORT                        318
#define CID_CHANGE_TOPIC                319
#define CID_FILE_LIST                   320
#define CID_CONF_NAME                   321
#define CID_TOPIC_NAME                  322
#define CID_CREATE_FLIST                323
#define CID_ASSUME                      324
#define CID_FILENAME                    325
#define CID_SIZE                        326
#define CID_DESCRIPTION                 327
#define CID_INSERT_DATE                 328
#define CID_TOPIC                       329
#define CID_SORT_ASCENDING              330
#define CID_SORT_DESCENDING             331
#define CID_SORT_NAME                   332
#define CID_SORT_DATE                   333
#define CID_SORT_SIZE                   334
#define CID_DATE                        335
#define CID_FLM_UPDATE                  336
#define CID_FLM_DATE                    337
#define CID_FLD_UPDATE                  338
#define CID_FLD_DATE                    339
#define CID_RENAME                      340
#define CID_FDIR_LIST                   341
#define CID_ORPHANS                     342
#define CID_IN_FLIST                    343
#define CID_ALL_FILES                   344
#define CID_HOLD                        345
#define CID_NOTIFY                      346
#define CID_CONFIGURE                   347
#define CID_SOURCE                      348
#define CID_PREVIOUS                    349
#define CID_NEXT                        350
#define CID_TAG_FILENAME                351
#define CID_TAG_SIZE                    352
#define CID_TAG_DATE                    353
#define CID_TAG_SOURCE                  354
#define CID_TAG_DESCRIPTION             355
#define CID_COMMENT_TEXT                356
#define CID_TAG_COMMENT_TEXT            357
#define CID_COMMENT_TYPE                358
#define CID_UNDO                        359
#define CID_FILE_DATE                   360
#define CID_TABBED_TEXT                 361
#define CID_OLDNAME                     362
#define CID_NEWNAME                     363
#define CID_UPLOAD_FLIST                364
#define CID_INSERT_CAPTION              365
#define CID_UPDATE                      366
#define CID_UPDATE_DATE                 367
#define CID_LINE_NUMBER                 368
#define CID_ERR_MEMO                    369
#define CID_ERR_COMMENT                 370
#define CID_ERR_INDENTED                371
#define CID_ERR_DISCARD                 372
#define CID_ABORT                       373
#define CID_ERR_TEXT_1                  374
#define CID_ERR_TEXT_2                  375
#define CID_ERR_TEXT_3                  376
#define CID_ERR_TEXT_4                  377
#define CID_CANCEL_ALL                  383
#define CID_FLIST_SORT_DESCENDING       384
#define CID_CONFIRM_FLIST               385
#define CID_LEAVE_FDIR                  386
#define CID_CONFIRM_FDIR                387
#define CID_DELETE_ALL_FDIR             388
#define CID_ABOUT_TEXT_FLIST            389
#define CID_UPDATE_MAIL_DIR             392
#define CID_UPDATE_UPLOAD               393
#define CID_LOCAL                       395
#define CID_DUP_TEXT                    396
#define CID_DUP_REPLACE                 397
#define CID_DUP_DUPLICATE               398
#define CID_ADD                         399
#define CID_CONF_DESCRIPTION            400
#define CID_TOPIC_DESCRIPTION           401
#define CID_CONF_OPEN                   402
#define CID_CONF_CLOSED                 403
#define CID_CONF_CONFIDENTIAL           404
#define CID_TOPIC_FLIST                 405
#define CID_TOPIC_READONLY              406
#define CID_CONF_DESC_TAG               407
#define CID_TOPIC_DESC_TAG              408
#define CID_TOPIC_SIZE                  409
#define CID_TOPIC_UPDATED               410
#define CID_FLS_UPDATE                  411
#define CID_FLS_DATE                    412
#define CID_ABOUT_TEXT_CONF             413
#define CID_ABOUT_TEXT_TOPIC            414
#define CID_ABOUT_FLIST                 415
#define CID_ABOUT_CONF                  416
#define CID_ABOUT_TOPIC                 417
#define CID_DUP_CANCEL                  418
#define CID_DLL_INFO                    419
#define CID_HCTOOLS_VERSION             420
#define CID_WINHORUS_VERSION            421
#define CID_NOTIFY_SINGLE               422
#define CID_DATE_FORMAT                 423
#define CID_DOWNLOAD_DIR                424
#define CID_DOWNLOAD_BROWSE             425
#define CID_UPLOAD_DIR                  426
#define CID_UPLOAD_BROWSE               427
#define CID_CONFIRM_ALL_FDIR            428
#define CID_CONFIRM_FLIST_FDIR          429
#define CID_CONFIRM_NONE_FDIR           430
#define CID_MENU_PREFIX                 431
#define CID_ABOUT_TEXT_CONFIGURE        432
#define CID_REMEMBER_UP                 433
#define CID_NOTIFY_MULTIPLE             434
#define CID_MESSAGE_TITLE               435
#define CID_EDIT_SEED                   436
#define CID_FLIST_SORT_NAME             437
#define CID_FLIST_SORT_DATE             438
#define CID_FLIST_SORT_SIZE             439
#define CID_FLIST_SORT_ASCENDING        440
#define CID_NOTIFY_SIGNATURE            441
#define CID_TOPIC_MAX                   442
#define CID_TOPIC_FREE                  443
#define CID_UPDATE_MANUAL               444
#define CID_UPDATE_PERIODIC             445
#define CID_UPDATE_ALWAYS               446
#define CID_UPDATE_DAYS                 447
#define CID_UPDATE_NEXT                 448
#define CID_UPDATE_TOPICS               449
#define CID_ACTION                      450
#define CID_PRUNE                       451
#define CID_TOPICSIZE_WARNING           452
#define CID_IMPORT                      453
#define CID_MESSAGE_LIST                454
#define CID_MESSAGE_TEXT                455
#define CID_CANDIDATE_MESSAGES          456
#define CID_ALL_MESSAGES                457
#define CID_ROOT_MESSAGES               458
#define CID_FIELD_SELECT                459
#define CID_CONF_NOTE                   460
#define CID_TRANSFORM                   461
#define CID_RESET                       462
#define CID_RESET_TAG                   463
#define CID_TAG_DAYS                    464
#define CID_TOPICSIZE_THRESHOLD         465
#define CID_TOPICSIZE_ENABLE            466
#define CID_FLX_DATE                    467
#define CID_TOPICSIZE_TAG               468
#define CID_NOTIFY_SIZE                 469
#define CID_NOTIFY_UPPERCASE            470
#define CID_INSERT_FDIR                 471
#define CID_NOTIFY_OS_STATUS            472
#define CID_TOPIC_PERCENT_FULL          473
#define CID_LOCAL_TOPIC_DELETE          474
#define CID_UPDATE_TOPIC_FRAME          475
#define CID_AUTO_NOTIFY                 476
#define CID_DATE_EXAMPLE                477
#define CID_STAT_LIST                   478
#define CID_STAT_ALL                    479
#define CID_STAT_SELECTED               480
#define CID_INSERT_FILEPOOL             481
#define CID_INSERT_MAIL_DIR             482
#define CID_INSERT_UPLOAD               483
#define CID_INSERT_NOTIFICATION         484
#define CID_INSERT_BLANK_LINE           485
#define CID_INSERT_COMMENT              486
#define CID_INSERT_INDENTED             487
#define CID_INSERT_MEMO                 488
#define CID_APPEND_FDIR                 489
#define CID_APPEND_FILEPOOL             490
#define CID_APPEND_MAIL_DIR             491
#define CID_APPEND_UPLOAD               492
#define CID_APPEND_NOTIFICATION         493
#define CID_APPEND_BLANK_LINE           494
#define CID_APPEND_COMMENT              495
#define CID_APPEND_INDENTED             496
#define CID_APPEND_MEMO                 497
#define IDT_MOD                         498
#define IDT_STAT                        499
#define IDT_FDIR                        500
#define IDT_VIEW                        501
#define IDC_APPTITLE                    1003
#define IDC_COPYRIGHT                   1004
#define CID_FDESCRIPTION                1004
#define CID_NOTIFY_PROMPT               1005
#define CID_SIG                         6018
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
